version: '3.8'

services:
  db:
    image: mysql 
    container_name: mi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345 
      MYSQL_DATABASE: Personas
      MYSQL_USER: root                
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:
